---
name: Reusable unit test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  test-setup-go:
    strategy:
      fail-fast: false
      matrix:
        attempt: [1,2,3,4,5,6,7,8,9,10]
        #,11,12,13,14,15,16,17,18,19,20]
    runs-on: actuated-arm64-2cpu-4gb
    steps:
      - uses: actions/checkout@v4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"

      - name: Look into the tool cache before setup-go
        run: |
          sudo find / -name go | grep bin || echo "go binary not found in root"
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
          cache: true
          check-latest: false

      - name: Look into the tool cache after setup-go
        run: |
          sudo find / -name go | grep bin || echo "go binary not found in root"
      - name: Find where go was put
        run: |
          which go

      - name: Run go version
        run: |
          go version

      - name: Run tests
        run: go test ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
